name: Hash Test Production
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Redeploy 1
  #       uses: fjogeleit/http-request-action@v1.16.1
  #       with:
  #         url: ""
  #         method: "POST"
  #         timeout: 600000
